Repository CodeChain-io/codechain-sdk-js, pull requests merged in 2018-10, with the labels that each got.

#210 Add the example of mini helicopter for Saluki
  examples/saluki/helicopter/helicopter.js
  examples/saluki/helicopter/mint-asset.js
Labels: documentation

#220 Fix a bug in encodeSignatureTag()
  src/__test__/SignatureTag.spec.ts
  src/core/transaction/AssetTransferTransaction.ts
  src/utils.ts
Labels: bug, test

#222 Update the version of codechain-primitives
  package.json
  src/__test__/secp256k1.spec.ts
  src/key/__test__/LocalKeyStore.spec.ts
  src/key/__test__/MemoryKeyStore.spec.ts
Labels: enhancement

#223 Fix wrong address format in examples
  examples/saluki/create-asset-transfer-address.js
Labels: documentation

#224 Fix URLs in package.json
  package.json
Labels: documentation

#225 Remove unused deprecated functions
  src/core/Parcel.ts
  src/core/transaction/AssetTransferTransaction.ts
  src/key/P2PKH.ts
  src/key/P2PKHBurn.ts
Labels: breaking-change, maintenance

#228 Fix compiler warnings for integration tests
  integration_tests/Rpc.spec.ts
  integration_tests/SignedParcel.spec.ts
  integration_tests/Transaction.spec.ts
  integration_tests/examples.spec.ts
  integration_tests/module.spec.ts
  integration_tests/useRegistrar.spec.ts
Labels: test

#229 Make addBurns, addInputs, and addOutputs support an array as the firs…
  src/core/transaction/AssetTransferTransaction.ts
  src/core/types.ts
Labels: enhancement

#230 Make createAssetTransferOutput() support lockScriptHash and parameter…
  src/core/index.ts
Labels: enhancement

#236 Check whether the public key is null
  src/key/__test__/LocalKeyStore.spec.ts
Labels: test

#237 Show the reason when asset transaction fails
  examples/mint-and-burn.js
  examples/mint-and-transfer.js
Labels: test

#239 Hotfix for breaking RPC
  .travis.yml
  src/rpc/account.ts
Labels: bug

#238 Make examples use ES6
  examples/chain-send-parcel.js
  examples/create-account-with-keystore.js
  examples/create-account-with-rpc.js
  examples/create-account-with-secret.js
  examples/create-asset-transfer-address.js
  examples/get-balance.js
  examples/import-test-account.js
  examples/mint-and-transfer.js
  examples/mint-asset.js
  examples/saluki/create-asset-transfer-address.js
  examples/saluki/create-platform-address.js
  examples/saluki/mint-and-transfer.js
  examples/saluki/mint-asset.js
  examples/saluki/payment.js
  examples/send-parcel.js
  examples/send-signed-parcel-with-keystore.js
  examples/send-signed-parcel.js
  examples/set-regular-key.js
  examples/unlock-and-send-parcel.js
Labels: test

#241 Rename nonce to seq
  .travis.yml
  examples/chain-send-parcel.js
  examples/send-signed-parcel-with-keystore.js
  examples/send-signed-parcel.js
  examples/set-regular-key.js
  integration_tests/Rpc.spec.ts
  integration_tests/SignedParcel.spec.ts
  integration_tests/helper.ts
  integration_tests/sendSignedParcel.spec.ts
  integration_tests/setRegularKey.spec.ts
  integration_tests/useRegistrar.spec.ts
  src/core/Parcel.ts
  src/core/SignedParcel.ts
  src/core/__test__/Block.spec.ts
  src/core/__test__/Parcel.spec.ts
  src/core/__test__/SignedParcel.spec.ts
  src/key/index.ts
  src/rpc/__test__/invalid-response.spec.ts
  src/rpc/account.ts
  src/rpc/chain.ts
Labels: breaking-change, rpc

#242 Remove World
  .travis.yml
  examples/mint-and-burn.js
  examples/mint-and-transfer.js
  examples/mint-asset.js
  integration_tests/Rpc.spec.ts
  integration_tests/Transaction.spec.ts
  integration_tests/helper.ts
  integration_tests/useRegistrar.spec.ts
  src/core/AssetScheme.ts
  src/core/classes.ts
  src/core/index.ts
  src/core/transaction/AssetComposeTransaction.ts
  src/core/transaction/AssetDecomposeTransaction.ts
  src/core/transaction/AssetMintTransaction.ts
  src/core/transaction/AssetTransferTransaction.ts
  src/core/transaction/CreateWorldTransaction.ts
  src/core/transaction/SetWorldOwnersTransaction.ts
  src/core/transaction/SetWorldUsersTransaction.ts
  src/core/transaction/Transaction.ts
  src/core/transaction/__test__/AssetMintTransaction.spec.ts
  src/core/transaction/__test__/CreateWorldTransaction.spec.ts
  src/core/transaction/__test__/SetWorldOwnersTransaction.spec.ts
  src/core/transaction/__test__/SetWorldUsersTransaction.spec.ts
  src/rpc/__test__/invalid-response.spec.ts
  src/rpc/chain.ts
Labels: breaking-change

#243 Change AssetTransactionGroup to AssetTransaction
  .travis.yml
  examples/mint-and-burn.js
  examples/mint-and-compose-and-decompose.js
  examples/mint-and-compose.js
  examples/mint-and-transfer.js
  examples/mint-asset.js
  integration_tests/Rpc.spec.ts
  integration_tests/Transaction.spec.ts
  integration_tests/helper.ts
  integration_tests/sendSignedParcel.spec.ts
  integration_tests/useRegistrar.spec.ts
  src/core/Parcel.ts
  src/core/__test__/Parcel.spec.ts
  src/core/action/Action.ts
  src/core/action/AssetTransaction.ts
  src/core/action/AssetTransactionGroup.ts
  src/core/classes.ts
  src/core/index.ts
  src/rpc/chain.ts
  tslint.json
Labels: breaking-change
