Repository CodeChain-io/codechain-sdk-js, pull requests merged in 2019-03, with the labels that each got.

#340 Make UnwrapCCC specify the receiver
  .travis.yml
  examples/wrap-ccc-and-unwrap-ccc.js
  src/core/index.ts
  src/core/transaction/UnwrapCCC.ts
  src/core/transaction/json.ts
Labels: breaking-change

#341 Add chain RPC calls
  examples/execute-tx.js
  src/rpc/chain.ts
Labels: enhancement

#327 Update the primitives version
  integration_tests/useApprover.spec.ts
  package.json
  src/core/Asset.ts
  src/core/AssetScheme.ts
  src/core/Transaction.ts
  src/core/index.ts
  src/core/transaction/Order.ts
  src/core/transaction/TransferAsset.ts
  src/core/types.ts
  src/key/index.ts
  src/rpc/account.ts
  src/rpc/chain.ts
Labels: maintenance

#346 Resolve any types
  src/core/Block.ts
  src/core/transaction/json.ts
Labels: maintenance

#355 Implements IncreaseAssetSupply.getMintedAsset()
  src/core/transaction/IncreaseAssetSupply.ts
Labels: core

#358 Fix the wrong RPC test
  src/rpc/__test__/invalid-response.spec.ts
Labels: test

#360 Implement toTokens for CHKTIMELOCK
  src/core/Script.ts
  src/core/__test__/Script.spec.ts
Labels: enhancement
