Repository CodeChain-io/codechain-sdk-js, pull requests merged in 2019-02, with the labels that each got.

#305 Do not set a regular key for the faucet address
  examples/set-regular-key.js
  integration_tests/Rpc.spec.ts
  integration_tests/useApprover.spec.ts
Labels: test

#304 Add expiration field to transactions
  .travis.yml
  src/core/Asset.ts
  src/core/index.ts
  src/core/transaction/TransferAsset.ts
  src/core/transaction/json.ts
Labels: breaking-change, core, test

#308 Rename Parcel to Transaction
  src/core/__test__/SignedTransaction.spec.ts
  src/core/__test__/Transaction.spec.ts
Labels: test

#309 Disable ComposeAsset/DecomposeAsset
  integration_tests/examples.spec.ts
  src/core/index.ts
  src/core/transaction/ComposeAsset.ts
  src/core/transaction/DecomposeAsset.ts
Labels: breaking-change

#310 Add the sender's address to WrapCCC
  .travis.yml
  examples/wrap-ccc-and-unwrap-ccc.js
  examples/wrap-ccc.js
  src/core/index.ts
  src/core/transaction/WrapCCC.ts
  src/core/transaction/json.ts
Labels: breaking-change

#312 Make getInvoice return a boolean instead of an object
  .travis.yml
  examples/mint-and-burn.js
  examples/mint-and-change-scheme.js
  examples/mint-and-transfer-with-order.js
  examples/mint-and-transfer.js
  examples/wrap-ccc-and-unwrap-ccc.js
  integration_tests/Rpc.spec.ts
  integration_tests/useApprover.spec.ts
  src/core/__test__/Invoice.spec.ts
  src/core/classes.ts
  src/core/index.ts
  src/rpc/__test__/invalid-response.spec.ts
  src/rpc/chain.ts
Labels: breaking-change

#316 Change the EcdsaSignature type from the rsv interface to string
  integration_tests/Rpc.spec.ts
  src/__test__/secp256k1.spec.ts
  src/core/SignedTransaction.ts
  src/core/Transaction.ts
  src/core/__test__/Transaction.spec.ts
  src/core/transaction/Remove.ts
  src/core/transaction/Store.ts
  src/key/MemoryKeyStore.ts
  src/key/__test__/LocalKeyStore.spec.ts
  src/key/__test__/MemoryKeyStore.spec.ts
  src/utils.ts
Labels: breaking-change, util

#317 Implement getErrorHint RPC
  src/rpc/chain.ts
Labels: rpc

#331 Add users field to CreateShard
  .travis.yml
  src/core/index.ts
  src/core/transaction/CreateShard.ts
  src/core/transaction/json.ts
Labels: breaking-change

#330 Rename the hash() of Transaction to unsignedHash
  src/core/SignedTransaction.ts
  src/core/Transaction.ts
  src/core/__test__/Transaction.spec.ts
  src/core/transaction/WrapCCC.ts
  src/key/index.ts
  src/rpc/chain.ts
Labels: breaking-change

#332 Add an example for the Custom transaction
  examples/send-custom-transaction.ts
Labels: test

#333 Fix the filename of the custom transaction example
  examples/send-custom-transaction.js
Labels: test

#335 Change examples to special users be active account
  examples/create-shard-and-set-owners.js
  examples/create-shard-and-set-users.js
  examples/mint-and-change-scheme.js
Labels: test

#336 Add an invoice field to SignedTransaction
  .travis.yml
  src/core/SignedTransaction.ts
  src/core/transaction/json.ts
Labels: rpc

#337 Rename invoice to result
  .travis.yml
  API.md
  examples/chain-send-tx.js
  examples/create-shard-and-mint.js
  examples/create-shard-and-set-owners.js
  examples/create-shard-and-set-users.js
  examples/mint-and-burn.js
  examples/mint-and-change-scheme.js
  examples/mint-and-compose-and-decompose.js
  examples/mint-and-compose.js
  examples/mint-and-increase-asset-supply.js
  examples/mint-and-transfer-with-order.js
  examples/mint-and-transfer.js
  examples/mint-asset.js
  examples/send-custom-transaction.js
  examples/send-signed-tx.js
  examples/send-tx.js
  examples/set-regular-key.js
  examples/store-and-remove.js
  examples/unlock-and-send-tx.js
  examples/wrap-ccc-and-unwrap-ccc.js
  examples/wrap-ccc.js
  integration_tests/Rpc.spec.ts
  integration_tests/setRegularKey.spec.ts
  integration_tests/useApprover.spec.ts
  src/core/Block.ts
  src/core/SignedTransaction.ts
  src/core/__test__/Block.spec.ts
  src/core/transaction/json.ts
  src/rpc/__test__/invalid-response.spec.ts
  src/rpc/chain.ts
Labels: breaking-change, rpc

#338 Remove redundant implementation
  src/rpc/chain.ts
Labels: maintenance
