Repository CodeChain-io/codechain-sdk-js, pull requests merged in 2019-04, with the labels that each got.

#364 Remove the deprecated networkId option
  src/index.ts
Labels: breaking-change

#366 Remove the transactionFee option and change the default fee to the minimum
  examples/create-shard-and-mint.js
  src/index.ts
  src/rpc/__test__/invalid-response.spec.ts
  src/rpc/account.ts
  src/rpc/chain.ts
  src/rpc/index.ts
Labels: breaking-change

#369 Fix getErrorHint()
  src/rpc/chain.ts
Labels: bug

#370 Add seq to ChangeAssetScheme and IncreaseAssetSupply
  .travis.yml
  src/core/AssetScheme.ts
  src/core/index.ts
  src/core/transaction/ChangeAssetScheme.ts
  src/core/transaction/IncreaseAssetSupply.ts
  src/core/transaction/json.ts
Labels: bug

#376 Add CHKMULTISIG opcode
  src/core/Script.ts
Labels: core

#378 Fix Block.getSize()
  src/core/Block.ts
Labels: bug
